# -*- coding: utf-8 -*-
"""AI and neural networks assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mlXuQj4Gc8Q0CBEriuGpI0X-uXMq6Xfo
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

"""Loading and Exploring the MNIST Dataset"""

(x_train, y_train), (x_test, y_test) = mnist.load_data()

"""Dataset Shape"""

print("Training images shape:", x_train.shape)
print("Training labels shape:", y_train.shape)
print("Test images shape:", x_test.shape)
print("Test labels shape:", y_test.shape)

"""Exploring Labels"""

print("Unique labels:", np.unique(y_train))

"""Visualising Sample Images"""

plt.figure(figsize=(8,4))
for i in range(8):
    plt.subplot(2,4,i+1)
    plt.imshow(x_train[i], cmap='gray')
    plt.title(f"Label: {y_train[i]}")
    plt.axis('off')
plt.show()

"""2.4 Normalising the Data"""

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

"""Model Implementation

4.1 Model Builder Function
"""

def build_model(hidden_activation):
    model = Sequential([
        Flatten(input_shape=(28, 28)),
        Dense(256, activation=hidden_activation),
        Dense(256, activation=hidden_activation),
        Dense(128, activation=hidden_activation),
        Dense(128, activation=hidden_activation),
        Dense(64, activation=hidden_activation),
        Dense(64, activation=hidden_activation),
        Dense(10, activation='softmax')
    ])

    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

"""5. Training Model

1 – Sigmoid Activation
"""

sigmoid_model = build_model('sigmoid')

history_sigmoid = sigmoid_model.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.1
)

sigmoid_test_loss, sigmoid_test_acc = sigmoid_model.evaluate(
    x_test, y_test
)

print("Sigmoid Test Accuracy:", sigmoid_test_acc)

"""6. Training Model 2 –

Tanh Activation
"""

tanh_model = build_model('tanh')

history_tanh = tanh_model.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.1
)

tanh_test_loss, tanh_test_acc = tanh_model.evaluate(
    x_test, y_test
)

print("Tanh Test Accuracy:", tanh_test_acc)

"""7. Performance Comparison Plots"""

plt.figure(figsize=(10,5))
plt.plot(history_sigmoid.history['val_accuracy'], label='Sigmoid')
plt.plot(history_tanh.history['val_accuracy'], label='Tanh')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.title('Validation Accuracy Comparison')
plt.legend()
plt.grid(True)
plt.show()

